notifications:
  email: false

language: node_js

node_js:
  - '0.12'
  - '4'
  - 'stable'

script:
  - npm run lint
  - npm run test

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
